SELECT * FROM customer;

-- What is the total revenue generated by male vs female customers?

SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer
GROUP BY gender;


-- Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= ( SELECT AVG(purchase_amount)
FROM customer
);


-- Which are the top 5 products with the highest average reviews rating?

SELECT item_purchased As Products, ROUND(AVG(review_rating::numeric),2) AS "Review Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Compare the average Purchases Amounts between Standard and Express Shipping.

SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type;


-- Do subscribed customers spend more? Compare the average spend and total revenue between 
-- subscirber and non-subscribers.

SELECT COUNT(customer_id) AS "Customers",subscription_status, ROUND(AVG(purchase_amount),2) AS "Average Spend",
SUM(purchase_amount) AS "Total Revenue"
FROM customer
GROUP BY subscription_status;


-- Which 5 Products have the highest percentage of purchases with discount applied?

SELECT item_purchased AS "Product",
ROUND(100 * SUM( CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END ) / COUNT(*),2) AS customer_rate
FROM customer
GROUP BY item_purchased
ORDER BY customer_rate DESC		
LIMIT 5;


-- What are the top 3 most purchased products within each category?

WITH product_cat AS(
SELECT category,item_purchased,
COUNT(*) AS total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
FROM customer
GROUP BY item_purchased,category

)

SELECT rnk,item_purchased,category,total_orders
FROM product_cat
WHERE rnk <=3;


-- Segment customers into New, Returning and Loyal based on their total
-- number of previous purches, and show the count of each segment.

WITH customer_seg AS(
SELECT customer_id, previous_purchases,
CASE
WHEN previous_purchases = 1 THEN 'New Customer'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Return Customers'
ELSE 'Loyal Customers' END AS Customer_segmentation
FROM customer
)

SELECT Customer_segmentation, COUNT(*) AS "Number of Customer"
FROM customer_seg
GROUP BY Customer_segmentation


-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

WITH customer_type AS(
SELECT customer_id,previous_purchases,
CASE
    WHEN subscription_status = 'Yes' AND previous_purchases > 5 THEN 'Subscriber buyers' ELSE 'Non Subscriber buyers' 
	END AS subscription_status
FROM customer
)

SELECT subscription_status, COUNT(*) AS "Repeat Buyers"
FROM customer_type
GROUP BY subscription_status;


-- What is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
